In [25]:
import numpy as np
import pandas as pd
#import statistics as st

In [26]:
df=pd.read_csv("C:\\Users\\jit16\\Downloads\\DSBDA from bhushan\\Mall_Customers.csv")

In [27]:
df

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [28]:
df.mean(numeric_only=True)

CustomerID                100.50
Age                        38.85
Annual Income (k$)         60.56
Spending Score (1-100)     50.20
dtype: float64

In [29]:
df['Age'].mean()

np.float64(38.85)

In [30]:
df.mean(axis=1,numeric_only=True)[0:1]

0    18.5
dtype: float64

In [31]:
df.mean(axis=0 , numeric_only= True)[0:2]

CustomerID    100.50
Age            38.85
dtype: float64

In [32]:
df.median(numeric_only=True)

CustomerID                100.5
Age                        36.0
Annual Income (k$)         61.5
Spending Score (1-100)     50.0
dtype: float64

In [33]:
df['Age'].median()

np.float64(36.0)

In [34]:
df.mode()

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
0             1  Female  32.0                54.0                    42.0
1             2     NaN   NaN                78.0                     NaN
2             3     NaN   NaN                 NaN                     NaN
3             4     NaN   NaN                 NaN                     NaN
4             5     NaN   NaN                 NaN                     NaN
..          ...     ...   ...                 ...                     ...
195         196     NaN   NaN                 NaN                     NaN
196         197     NaN   NaN                 NaN                     NaN
197         198     NaN   NaN                 NaN                     NaN
198         199     NaN   NaN                 NaN                     NaN
199         200     NaN   NaN                 NaN                     NaN

[200 rows x 5 columns]

In [35]:
df.min()

CustomerID                     1
Genre                     Female
Age                           18
Annual Income (k$)            15
Spending Score (1-100)         1
dtype: object

In [36]:
df.max()

CustomerID                 200
Genre                     Male
Age                         70
Annual Income (k$)         137
Spending Score (1-100)      99
dtype: object

In [37]:
df.std(numeric_only=True)

CustomerID                57.879185
Age                       13.969007
Annual Income (k$)        26.264721
Spending Score (1-100)    25.823522
dtype: float64

In [38]:
df.groupby('Genre')['Age'].describe()

        count       mean        std   min    25%   50%   75%   max
Genre
Female  112.0  38.098214  12.644095  18.0  29.00  35.0  47.5  68.0
Male     88.0  39.806818  15.514812  18.0  27.75  37.0  50.5  70.0

In [39]:
df1=df.rename(columns={'Annual Income (k$)' : 'Income'})

In [40]:
df1

     CustomerID   Genre  Age  Income  Spending Score (1-100)
0             1    Male   19      15                      39
1             2    Male   21      15                      81
2             3  Female   20      16                       6
3             4  Female   23      16                      77
4             5  Female   31      17                      40
..          ...     ...  ...     ...                     ...
195         196  Female   35     120                      79
196         197  Female   45     126                      28
197         198    Male   32     126                      74
198         199    Male   32     137                      18
199         200    Male   30     137                      83

[200 rows x 5 columns]

In [41]:
df1.groupby('Age').Income.apply(list)

Age
18                                   [33, 48, 59, 65]
19                   [15, 46, 48, 63, 64, 65, 74, 81]
20                               [16, 21, 37, 61, 73]
21                               [15, 30, 33, 54, 62]
22                                       [17, 20, 57]
23                           [16, 18, 29, 54, 62, 70]
24                                   [20, 38, 39, 60]
25                                       [24, 72, 77]
26                                           [54, 62]
27                           [40, 46, 60, 67, 78, 88]
28                                  [76, 77, 87, 101]
29                               [28, 40, 73, 79, 98]
30                      [19, 34, 78, 78, 88, 99, 137]
31                   [17, 25, 39, 40, 43, 70, 72, 81]
32    [48, 60, 73, 75, 76, 77, 87, 97, 103, 126, 137]
33                                      [42, 86, 113]
34                              [58, 78, 78, 78, 103]
35              [18, 19, 21, 23, 24, 28, 74, 93, 120]
36                          [37, 85, 87, 87, 87, 103]
37                                       [20, 78, 97]
38                          [54, 64, 67, 71, 78, 113]
39                                       [69, 71, 78]
40                           [29, 54, 60, 69, 71, 87]
41                                          [99, 103]
42                                           [34, 86]
43                                       [48, 71, 78]
44                                           [73, 78]
45                                      [28, 54, 126]
46                                       [25, 54, 98]
47                          [43, 49, 60, 71, 78, 120]
48                               [39, 54, 60, 61, 77]
49                       [33, 39, 42, 54, 62, 62, 65]
50                               [40, 43, 58, 67, 85]
51                                           [44, 67]
52                                           [23, 88]
53                                           [33, 46]
54                                  [28, 47, 63, 101]
55                                               [57]
56                                               [79]
57                                           [54, 75]
58                                           [20, 88]
59                                   [43, 54, 71, 93]
60                                       [30, 50, 50]
63                                           [48, 65]
64                                               [19]
65                                           [38, 63]
66                                           [63, 63]
67                                   [19, 47, 54, 62]
68                                       [48, 59, 63]
69                                               [44]
70                                           [46, 49]
Name: Income, dtype: object

In [42]:
#import matplotlib as plt

In [43]:
iris=pd.read_csv("C:\\Users\\jit16\\Downloads\\DSBDA from bhushan\\Iris.csv")

In [44]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,NaN,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [45]:
iris['Species'].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [46]:
print("Iris-setosa")

Iris-setosa

In [47]:
setosa=iris['Species']=='Iris-setosa'

In [48]:
iris[setosa].describe()

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      49.000000      50.00000
mean   25.50000        5.00600      3.418000       1.467347       0.24400
std    14.57738        0.35249      0.381024       0.173671       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.600000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [49]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     149.000000    150.000000
mean    75.500000       5.843333      3.054000       3.775168      1.198667
std     43.445368       0.828066      0.433594       1.758720      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.400000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000